apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    openshift.io/display-name: vLLM GPU for Lightspeed POC
  name: vllm-gpu
  namespace: lightspeed-poc
  labels:
    opendatahub.io/dashboard: "true"
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  containers:
    - args:
        - --model
        - Qwen/Qwen2.5-0.5B-Instruct
        - --enable-auto-tool-choice
        - --tool-call-parser
        - llama3_json
        - --chat-template
        - /mnt/chat-template/tool_chat_template_llama3.2_json.jinja
        - --download-dir
        - /tmp/models-cache
        - --port
        - "8080"
        - --max-model-len
        - "8192"
        - --gpu-memory-utilization
        - "0.9"
        - --dtype
        - half
      # Using public vLLM image - Red Hat image tag v0.6.5-2024b-6 not found
      # If you have access to Red Hat images, try: quay.io/modh/vllm:stable
      image: quay.io/modh/vllm:rhoai-2.20-cuda
      name: kserve-container
      env:
        - name: HF_HUB_OFFLINE
          value: "false"
        - name: TRANSFORMERS_OFFLINE
          value: "false"
        - name: HF_DATASETS_OFFLINE
          value: "false"
        - name: HF_HOME
          value: /mnt/models-cache/hf_home
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        - name: VLLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: vllm-api-key-secret
              key: key
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
      volumeMounts:
        - name: chat-template
          mountPath: /mnt/chat-template
        - name: models-cache
          mountPath: /mnt/models-cache
        - name: vllm-cache
          mountPath: /.cache
      resources:
        limits:
          nvidia.com/gpu: 1
          cpu: "4"
          memory: 12Gi
        requests:
          nvidia.com/gpu: 1
          cpu: "2"
          memory: 10Gi
  volumes:
    - name: chat-template
      configMap:
        name: vllm-chat-template
    - name: models-cache
      emptyDir: {}
    - name: vllm-cache
      emptyDir: {}
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
